from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('ingreso', views.ingreso, name="ingreso"),
    path('salida', views.salida, name="salida"),
    path('seguridad', views.seguridad, name="seguridad"),
    path('gestion_usuarios', views.gestion_usuarios, name="gestion_usuarios"),
    path('gestion_roles', views.gestion_roles, name="gestion_roles"),
    path('gestion_permisos', views.gestion_permisos, name="gestion_permisos"),
    path('inicio', views.inicio, name="inicio"),
    path('add_usuario', views.add_usuario, name="add_usuario"),
    path('add_rol', views.add_rol, name="add_rol"),
    path('add_permiso', views.add_permiso, name="add_permiso"),
    path('mod_usuario', views.mod_usuario, name="mod_usuario"),
    path('alterar_permiso', views.alterar_permiso, name="alterar_permiso"),
    path('alterar_rol', views.alterar_rol, name="alterar_rol"),
    path('alterar_usuario', views.alterar_usuario, name="alterar_usuario"),
    path('cambiar_permiso', views.cambiar_permiso, name="cambiar_permiso"),
    path('cambiar_rol', views.cambiar_rol, name="cambiar_rol"),
    path('cambiar_usuario', views.cambiar_usuario, name="cambiar_usuario"),
    path('eliminar_permiso', views.eliminar_permiso, name="eliminar_permiso"),
    path('eliminar_rol', views.eliminar_rol, name="eliminar_rol"),
    path('eliminar_usuario', views.eliminar_usuario, name="eliminar_usuario"),
    path('gestion_proyectos', views.gestion_proyectos, name="gestion_proyectos"),
    path('add_proyecto', views.add_proyecto, name="add_proyecto"),
    path('ver_proyecto', views.ver_proyecto, name="ver_proyecto"),
    path('eliminar_proyecto', views.eliminar_proyecto, name="eliminar_proyecto"),
    path('eliminar_user_proyecto', views.eliminar_user_proyecto, name="eliminar_user_proyecto"),
    path('add_user_proyecto', views.add_user_proyecto, name="add_user_proyecto"),
    path('ver_backlog', views.ver_backlog, name="ver_backlog"),
    path('ver_sprint', views.ver_sprint, name="ver_sprint"),
    path('add_us', views.add_us, name="add_us"),
    path('add_sp', views.add_sp, name="add_sp"),
    path('cambiar_estado_us', views.cambiar_estado_us, name="cambiar_estado_us"),
    path('ver_us', views.ver_us, name="ver_us"),
    path('iniciar_sprint', views.iniciar_sprint, name="iniciar_sprint"),
    path('finalizar_sprint', views.finalizar_sprint, name="finalizar_sprint")
]