# Generated by Django 4.1 on 2022-09-09 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectos', '0002_remove_rol_id_permiso_rol_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionProyectos.rol'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UsuarioRol',
        ),
    ]
