# Generated by Django 4.1 on 2022-09-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectos', '0004_backlog_userstory_proyecto_backlog_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('EN CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado')], default='EN CURSO', max_length=50),
        ),
    ]
