# Generated by Django 4.1 on 2022-09-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectos', '0005_proyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
    ]
