# Generated by Django 4.1 on 2022-09-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectos', '0006_proyecto_fecha_fin_proyecto_fecha_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstory',
            old_name='usuarios',
            new_name='usuario',
        ),
    ]
