# Generated by Django 4.1 on 2022-10-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectos', '0007_rename_usuarios_userstory_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
    ]
