# Generated by Django 4.1 on 2022-10-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectos', '0008_userstory_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='backlog',
        ),
    ]
