# Generated by Django 4.1 on 2022-10-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectos', '0010_sprint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sprint',
        ),
    ]
