# Generated by Django 4.1 on 2022-10-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectos', '0012_delete_userstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.IntegerField(default=15)),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProyectos.backlog')),
            ],
        ),
    ]
