# Generated by Django 4.1 on 2022-10-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectos', '0013_sprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(null=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProyectos.sprint')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProyectos.usuario')),
            ],
        ),
    ]
