# Generated by Django 4.1 on 2022-10-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectos', '0014_userstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='estado',
            field=models.CharField(choices=[('EN CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado')], default='EN CURSO', max_length=50),
        ),
    ]
