# Generated by Django 4.1 on 2022-10-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectos', '0015_sprint_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
    ]
