# Generated by Django 4.1 on 2022-10-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectos', '0016_sprint_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
    ]
