# Generated by Django 4.1 on 2022-10-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectos', '0017_sprint_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='estado',
            field=models.CharField(choices=[('EN CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado')], default='EN CURSO', max_length=50),
        ),
    ]
