# Generated by Django 4.1 on 2022-10-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectos', '0018_userstory_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=50),
        ),
    ]
