# Generated by Django 4.1.2 on 2022-10-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectos', '0019_alter_userstory_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=50),
        ),
    ]
